name: Test project in a PR
on: [pull_request]
jobs:
  test_mac:
    runs-on: macos-latest
    defaults:
      run:
        # Run everything from within the craft_pro project directory
        working-directory: ./craft_pro
    steps:
      # Checkout the PR branch
      - uses: actions/checkout@v3

      # Setup Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      # Download all the packages that the app uses
      - run: flutter pub get

      # TODO: run static analysis here when we get to zero analysis warnings

      # Run all tests
      - run: flutter test

  test_windows:
    runs-on: windows-latest
    defaults:
      run:
        # Run everything from within the craft_pro project directory
        working-directory: ./craft_pro
    steps:
      # Checkout the PR branch
      - uses: actions/checkout@v3

      # Setup Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Download all the packages that the app uses
      - run: flutter pub get

      # TODO: run static analysis here when we get to zero analysis warnings

      # Run all tests
      - run: flutter test

  test_linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Run everything from within the craft_pro project directory
        working-directory: ./craft_pro
    steps:
      # Checkout the PR branch
      - uses: actions/checkout@v3

      # Setup Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Download all the packages that the app uses
      - run: flutter pub get

      # TODO: run static analysis here when we get to zero analysis warnings

      # Run all tests
      - run: flutter test
