name: Pull Request (Opened)

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  assign_author:
    name: Assign Author to the Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Assign Author to the Pull Request
        uses: technote-space/assign-author@6252488282b99652aef47451a353eb88aea24666
