name: Review Assign

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, edited, closed] # synchronize is specified for check

jobs:
  assign:
    name: Use this action for check
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
      - name: Use this action
        uses: ./
        id: assign
        with:
          assignees: ${{ github.actor }}
          bot-accounts: some-bot
          reviewers: champ96k
          #max-num-of-reviewers: 2 
          draft-keyword: wip
          ready-comment: 'Ready for review :rocket: `<reviewers>`'
      - name: Show result
        if: always()
        run: echo '${{ steps.assign.outputs.result }}'
  assign-closed:
    name: Use this action for check [closed]
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Use this action
        uses: hkusu/review-assign-action@master
        id: assign
        with:
          merged-comment: 'It was merged. Thanks for your review :wink: `<reviewers>`'
      - name: Show result
        if: always()
        run: echo '${{ steps.assign.outputs.result }}'